header:
  license:
    spdx-id: MPL-2.0
    content: |
      SPDX-License-Identifier: MPL-2.0

      This Source Code Form is subject to the terms of the Mozilla Public
      License, v. 2.0. If a copy of the MPL was not distributed with this
      file, You can obtain one at https://mozilla.org/MPL/2.0/.

  paths:
    - "**"

  paths-ignore:
    - "3rdparty/**"
    - "3rdparty"
    - "web/**"
    - "web"
    - ".github/**"
    - "config/**"
    - ".gitignore"
    - ".gitmodules"
    - "meson.build"
    - "meson_options.txt"
    - "**/*.md"
    - "LICENSE"

  comment: on-failure
