# ==================== pipeline/encode - encoder pipeline (header-only) ====================
pipeline_encode_dep = declare_dependency(
  include_directories: include_directories('encode'),
)

# ==================== pipeline/decode - decoder pipeline (header-only) ====================
pipeline_decode_dep = declare_dependency(
  include_directories: include_directories('decode'),
)
