name: ci

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
        - name: "linux gcc11"
          os: ubuntu-22.04
          env: CXX="g++-11" CC="gcc-11"

        - name: "linux gcc-latest"
          os: ubuntu-latest

        - name: "linux clang14"
          os: ubuntu-22.04
          env: CXX="clang++" CC="clang"
          extra-packages: "clang"

        - name: "linux clang-latest"
          os: ubuntu-latest
          env: CXX="clang++" CC="clang"
          extra-packages: "clang"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libopencv-dev libglfw3-dev libgles2-mesa-dev meson ninja-build ${{ matrix.config.extra-packages }}

    - name: Configure Meson
      run: ${{ matrix.config.env }} meson setup build --prefix ${{ github.workspace }}/dist

    - name: Build
      run: ninja -C build && meson install -C build

    - name: Test
      run: meson test -C build --suite libcimbar --verbose

    - name: Usage test
      working-directory: ${{runner.workspace}}/libcimbar/test/py
      run: python3 -m unittest

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: libcimbar-${{ matrix.config.name }}-${{ github.sha }}
        path: ${{ github.workspace }}/dist/
        retention-days: 30

  cppcheck:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install cppcheck

    - name: run cppcheck
      run: cppcheck src/ tools/

